/* =========================================================
   CATÁLOGO COMPLETO — Documento Mestre + Atualização Oficial
   de Roletas e Categorização.
   9 roletas especializadas, 313 produtos ao todo.
   Olhos, Body Splash e Blush foram corrigidos conforme o
   documento de atualização; as demais roletas continuam iguais.
   marca: "" = não foi possível identificar a marca pelo nome.
   cor/funcao/combina ficam propositalmente em branco.
   ========================================================= */

const CATEGORIAS_ROLETA = {
  boca: { label: "Boca", emoji: "💋" },
  splash: { label: "Body Splash", emoji: "🌸" },
  olhos: { label: "Olhos", emoji: "👁️" },
  esmalte: { label: "Esmalte", emoji: "💅" },
  esmalte_efeito: { label: "Esmalte Efeito", emoji: "✨" },
  blush: { label: "Blush", emoji: "😊" },
  anel: { label: "Anel", emoji: "💍" },
  base: { label: "Base / Corretivo", emoji: "🧴" },
  cilios: { label: "Máscara de Cílios", emoji: "👁️" },
};

const CATALOGO = [
  { id: "boca_001", nome: "Guava Ginger", marca: "Guava", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_002", nome: "Guava Candy", marca: "Guava", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_003", nome: "Guava Amora", marca: "Guava", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_004", nome: "Guava Mocha", marca: "Guava", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_005", nome: "Guava Coral", marca: "Guava", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_006", nome: "Guava incolor", marca: "Guava", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_007", nome: "Sheglam Tattoo laranja", marca: "Sheglam", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_008", nome: "Sheglam Tattoo vermelho", marca: "Sheglam", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_009", nome: "Vizzela Pastor alemão", marca: "Vizzela", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_010", nome: "Eudora tint uva", marca: "Eudora", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_011", nome: "Melu Olinda Xodó", marca: "Melu", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_012", nome: "Natura gloss brilho", marca: "Natura", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_013", nome: "Quintal Seiva", marca: "Quintal", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_014", nome: "Melu Papaya", marca: "Melu", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_015", nome: "Oceane Ruby", marca: "Oceane", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_016", nome: "B.O.B Abacate", marca: "B.O.B", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_017", nome: "B.O.B Melancia", marca: "B.O.B", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_018", nome: "Dudah 001", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_019", nome: "Dudah 002", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_020", nome: "Dudah 003", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_021", nome: "Dudah 004", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_022", nome: "Dudah 005", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_023", nome: "Dudah 006", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_024", nome: "Dudah 007", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_025", nome: "Creamy Chai", marca: "Creamy", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_026", nome: "Creamy Latte", marca: "Creamy", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_027", nome: "Bauny Dreamy", marca: "Bauny", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_028", nome: "Bauny Sunny", marca: "Bauny", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_029", nome: "Dudah Gum", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_030", nome: "Dudah Peach fuzz", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_031", nome: "Dudah Brown sugar", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_032", nome: "Dudah Cinnamon rouge", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_033", nome: "Dudah Flash berry", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_034", nome: "Dudah Aurora shine", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_035", nome: "Dudah Golden hour", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_036", nome: "Dudah Rosy glitz", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_037", nome: "Dudah Cosmic grape", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_038", nome: "Dudah Golden sugar", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_039", nome: "Dudah Popstar", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_040", nome: "Dudah Birthday cake", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_041", nome: "Dudah Peach glaze", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_042", nome: "Dudah Boost babe", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_043", nome: "Ct1g Vintage", marca: "Ct1g", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_044", nome: "Ct1g Baile", marca: "Ct1g", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_045", nome: "Ct1g Atemporal", marca: "Ct1g", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_046", nome: "Dudah Berry", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_047", nome: "Dudah Coral", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_048", nome: "Dudah Rose", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_049", nome: "Dudah Red", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_050", nome: "Dudah Terracotta", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_051", nome: "Bt Harmony", marca: "Bt", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_052", nome: "Bt Spicy", marca: "Bt", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_053", nome: "Bmes Cacau 40%", marca: "Bmes", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_054", nome: "Bmes Cacau 60%", marca: "Bmes", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_055", nome: "Bmes Figo", marca: "Bmes", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_056", nome: "Vizzela Red mocha", marca: "Vizzela", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_057", nome: "Bt Nuts", marca: "Bt", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_058", nome: "Bt Espresso", marca: "Bt", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_059", nome: "Bt Wood", marca: "Bt", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_060", nome: "Bt Cinnamon", marca: "Bt", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_061", nome: "Mascavo Truffle", marca: "Mascavo", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_062", nome: "Mascavo Sugar candy", marca: "Mascavo", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_063", nome: "Bt Drink please", marca: "Bt", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_064", nome: "Bt Cute", marca: "Bt", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_065", nome: "Mascavo Peony", marca: "Mascavo", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_066", nome: "Granado Pitanga", marca: "Granado", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_067", nome: "Granado Guaraná", marca: "Granado", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_068", nome: "Granado Goiaba", marca: "Granado", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_069", nome: "Oceane lip morango", marca: "Oceane", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_070", nome: "Kiko lilás", marca: "Kiko", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_071", nome: "Dudah Peony", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_072", nome: "Dudah Sienna", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_073", nome: "Dudah Mocha", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_074", nome: "Mascavo Hot chocolate", marca: "Mascavo", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_075", nome: "Ag Profundo", marca: "Ag", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_076", nome: "Ag Suave", marca: "Ag", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_077", nome: "Guava stick avelã", marca: "Guava", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_078", nome: "Guava stick Café", marca: "Guava", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_079", nome: "Guava stick Coral", marca: "Guava", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_080", nome: "Guava stick Amora", marca: "Guava", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_081", nome: "Dudah Rosewood", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "boca_082", nome: "Dudah Coffee", marca: "Dudah", tipo: "labios", categoriaRoleta: "boca", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_001", nome: "Boticario Pessegura", marca: "Boticario", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_002", nome: "Boticario morango e leite", marca: "Boticario", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_003", nome: "Boticario Deleite", marca: "Boticario", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_004", nome: "Aura Venus love", marca: "Aura", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_005", nome: "Aura Radiant Hera", marca: "Aura", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_006", nome: "Aura Athena Glow", marca: "Aura", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_007", nome: "Eudora La Victorie intense", marca: "Eudora", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_008", nome: "Eudora Imensi", marca: "Eudora", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_009", nome: "Eudora Morango", marca: "Eudora", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_010", nome: "Eudora La victorie", marca: "Eudora", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_011", nome: "Natura Uma", marca: "Natura", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_012", nome: "Ct1g Pink", marca: "Ct1g", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_013", nome: "Eudora Diva", marca: "Eudora", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_014", nome: "Ofie melancia", marca: "Ofie", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_015", nome: "Ofie pistache", marca: "Ofie", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_016", nome: "Ofie algodão doce", marca: "Ofie", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_017", nome: "Natura Pitanga preta", marca: "Natura", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_018", nome: "Natura Ryo", marca: "Natura", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_019", nome: "Eudora La victorie creme", marca: "Eudora", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_020", nome: "Barbous Roses", marca: "Barbous", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_021", nome: "Barbous Living grace", marca: "Barbous", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_022", nome: "Barbous Icon", marca: "Barbous", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_023", nome: "YB Mermaid Kiss", marca: "YB", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_024", nome: "YB Milk dream", marca: "YB", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "splash_025", nome: "YB Caramel glow", marca: "YB", tipo: "outros", categoriaRoleta: "splash", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_001", nome: "Oceane Flame", marca: "Oceane", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_002", nome: "Oceane Romance", marca: "Oceane", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_003", nome: "Oceane Dreamer", marca: "Oceane", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_004", nome: "Oceane Soft peach", marca: "Oceane", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_005", nome: "Oceane Rose Quartz", marca: "Oceane", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_006", nome: "Bauny Sunny", marca: "Bauny", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_007", nome: "Bauny Dreamy", marca: "Bauny", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_008", nome: "Bt Off white", marca: "Bt", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_009", nome: "Dudah Red", marca: "Dudah", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_010", nome: "Dudah Berry", marca: "Dudah", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_011", nome: "Dudah Coral", marca: "Dudah", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_012", nome: "Oceane Taninn", marca: "Oceane", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_013", nome: "Oceane Aura", marca: "Oceane", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_014", nome: "Oceane Cork", marca: "Oceane", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_015", nome: "Bt Nuts", marca: "Bt", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_016", nome: "Bt Espresso", marca: "Bt", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_017", nome: "Bt Wood", marca: "Bt", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_018", nome: "Bmes Cacau 60%", marca: "Bmes", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_019", nome: "Bmes Figo", marca: "Bmes", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_020", nome: "Bmes Cacau 40%", marca: "Bmes", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_021", nome: "Bt Cinnamon", marca: "Bt", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_022", nome: "Vizzela Red mocha", marca: "Vizzela", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_023", nome: "Mascavo Peony", marca: "Mascavo", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_024", nome: "Bt Drink please", marca: "Bt", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_025", nome: "Bt Toffee", marca: "Bt", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_026", nome: "Sp colors", marca: "Sp colors", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_027", nome: "Sheglam Teeasure (Treasure)", marca: "Sheglam", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_028", nome: "Sheglam Stunner", marca: "Sheglam", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_029", nome: "Ct1g Miragem", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_030", nome: "Ct1g Elixir", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_031", nome: "Oceane Copper", marca: "Oceane", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_032", nome: "Dailus verde", marca: "Dailus", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_033", nome: "Ct1g Super marinho", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_034", nome: "Ct1g Submerso", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_035", nome: "Kiko azul 28", marca: "Kiko", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_036", nome: "Oceane Golden Brown", marca: "Oceane", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_037", nome: "Ct1g Super cobre", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_038", nome: "Ct1g Super vinho", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_039", nome: "Dior Pearly pink", marca: "Dior", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_040", nome: "Vizzela Cherry", marca: "Vizzela", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_041", nome: "Klasme brown", marca: "Klasme", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_042", nome: "Kiko 04", marca: "Kiko", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_043", nome: "Ct1g Metamorfose", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_044", nome: "Ct1g Delírio", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_045", nome: "Sephora Starry sky", marca: "Sephora", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_046", nome: "Oceane Silver", marca: "Oceane", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_047", nome: "Ct1g Super preto", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_048", nome: "Pink21 rosa", marca: "Pink21", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_049", nome: "Ct1g delineador preto", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_050", nome: "Ct1g Interestelar", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_051", nome: "Kiko 05", marca: "Kiko", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_052", nome: "Sheglam Lilac luster", marca: "Sheglam", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_053", nome: "Bt Teal", marca: "Bt", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_054", nome: "Ct1g Vintage", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_055", nome: "Ct1g Atemporal", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_056", nome: "Ct1g Baile", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_057", nome: "Dudah Rose", marca: "Dudah", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_058", nome: "Dudah Terracota", marca: "Dudah", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_059", nome: "Melu 01", marca: "Melu", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_060", nome: "Velvet preto", marca: "Velvet", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_061", nome: "Delineador preto", marca: "", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_062", nome: "Paleta sombras sheglam", marca: "", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_063", nome: "Paleta ct1g", marca: "", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_064", nome: "Paletas Romand Dusk to down", marca: "", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_065", nome: "Guava stick amora", marca: "Guava", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_066", nome: "Guava stick coral", marca: "Guava", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_067", nome: "Guava stick avelã", marca: "Guava", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_068", nome: "Guava stick café", marca: "Guava", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_069", nome: "Ct1g super marrom", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_070", nome: "Bt cinza Magnific wish", marca: "Bt", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_071", nome: "Sephora Waterfall", marca: "Sephora", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_072", nome: "Kiko azul 11", marca: "Kiko", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_073", nome: "Ruby K Titanium glam", marca: "Ruby K", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_074", nome: "Kiko cobre 03", marca: "Kiko", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_075", nome: "Ruby K Pearl Glam", marca: "Ruby K", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_076", nome: "Ruby rose preto", marca: "Ruby rose", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_077", nome: "Ct1g Epifania", marca: "Ct1g", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_078", nome: "QDB Rosaton", marca: "QDB", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_079", nome: "Kiko verde 08", marca: "Kiko", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_080", nome: "Oceane Golden", marca: "Oceane", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_081", nome: "Guava avelã", marca: "Guava", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_082", nome: "Guava Chocolate", marca: "Guava", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_083", nome: "Guava baunilha", marca: "Guava", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_084", nome: "Ruby k Rose glam", marca: "Ruby K", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "olhos_085", nome: "Essence verde", marca: "Essence", tipo: "olhos", categoriaRoleta: "olhos", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_001", nome: "Me encontra no letreiro", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_002", nome: "Rainha da selva de pedra", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_003", nome: "Ouro nude", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_004", nome: "Lavanda alma", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_005", nome: "Melissa", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_006", nome: "Rosa açaí", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_007", nome: "Verdelírio", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_008", nome: "Comigo ninguém cobre", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_009", nome: "Inspiração divina", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_010", nome: "Oi, sumida", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_011", nome: "Regras do jogo", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_012", nome: "Profundezas do meu eu", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_013", nome: "Espumante rosé", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_014", nome: "Metrópole noturna", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_015", nome: "A onça que habita em mim", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_016", nome: "Cafuné", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_017", nome: "Angélica", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_018", nome: "Roxo sem crise", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_019", nome: "Lágrima de unicórnio", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_020", nome: "Antes que Saturno volte", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_021", nome: "Discreto", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_022", nome: "Verdadeira camaleoa", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_023", nome: "Alento", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_024", nome: "Guerreira do arco-íris", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_025", nome: "Chuva cósmica", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_026", nome: "Carregada no básico", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_027", nome: "Nada óbvio", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_028", nome: "A.mar", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_029", nome: "Hot chocolate", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_030", nome: "Tromba de elefante", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_031", nome: "Caramelo quente", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_032", nome: "Diamante azul", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_033", nome: "Granulado rose", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_034", nome: "Lembranças", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_035", nome: "Chega e arrasa", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_036", nome: "Astral", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_037", nome: "Aura Prisma", marca: "Aura", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_038", nome: "Aura Magnética", marca: "Aura", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_039", nome: "Aura Quântica", marca: "Aura", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_040", nome: "Aura Astra", marca: "Aura", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_041", nome: "Aura Espectra", marca: "Aura", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_042", nome: "Aura Celestia", marca: "Aura", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_043", nome: "SolarIsa", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_044", nome: "Heartbeat", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_045", nome: "Patched up beauty", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_046", nome: "Forged in caos", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_047", nome: "Deep vintage", marca: "", tipo: "outros", categoriaRoleta: "esmalte", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_001", nome: "Lembranças", marca: "", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_002", nome: "Chega e arrasa", marca: "", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_003", nome: "Diamante azul", marca: "", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_004", nome: "Granulado rose", marca: "", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_005", nome: "Verdelírio", marca: "", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_006", nome: "Verdadeira camaleoa", marca: "", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_007", nome: "A onça que habita em mim", marca: "", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_008", nome: "Meu jardim mágico", marca: "", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_009", nome: "Top coat diamond gel", marca: "", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_010", nome: "Top coat fosco", marca: "", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_011", nome: "Top coat gel", marca: "", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_012", nome: "Aura Celestia", marca: "Aura", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_013", nome: "Aura Espectra", marca: "Aura", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_014", nome: "Aura Magnética", marca: "Aura", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_015", nome: "Aura Astra", marca: "Aura", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_016", nome: "Aura Quântica", marca: "Aura", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "esmalte_efeito_017", nome: "Aura Prisma", marca: "Aura", tipo: "outros", categoriaRoleta: "esmalte_efeito", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_001", nome: "Ct1g Atemporal", marca: "Ct1g", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_002", nome: "Dudah Rose", marca: "Dudah", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_003", nome: "Dudah Coral", marca: "Dudah", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_004", nome: "Dudah Berry", marca: "Dudah", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_005", nome: "Dudah Terracotta", marca: "Dudah", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_006", nome: "Dudah Red", marca: "Dudah", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_007", nome: "Bt Espresso", marca: "Bt", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_008", nome: "Vizzela Red mocha", marca: "Vizzela", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_009", nome: "Bt Cinnamon", marca: "Bt", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_010", nome: "Bmes Figo", marca: "Bmes", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_011", nome: "Bt Nuts", marca: "Bt", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_012", nome: "Rare Hope", marca: "Rare", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_013", nome: "Rare Happy", marca: "Rare", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_014", nome: "Bt Drink please", marca: "Bt", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_015", nome: "Mascavo Peony", marca: "Mascavo", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_016", nome: "Guava stick Coral", marca: "Guava", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_017", nome: "Guava stick Amora", marca: "Guava", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_018", nome: "Oceane Flame", marca: "Oceane", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_019", nome: "Oceane Dreamer", marca: "Oceane", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_020", nome: "Oceane Romance", marca: "Oceane", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_021", nome: "Bauny Dreamy", marca: "Bauny", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_022", nome: "Bauny Sunny", marca: "Bauny", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_023", nome: "Ct1g Vintage", marca: "Ct1g", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "blush_024", nome: "Ct1g Baile", marca: "Ct1g", tipo: "rosto", categoriaRoleta: "blush", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_001", nome: "Vivara Coração", marca: "Vivara", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_002", nome: "4 fininha dourada", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_003", nome: "4 torta prata", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_004", nome: "Torcida dourada", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_005", nome: "Torta aberta", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_006", nome: "Quadrada", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_007", nome: "Torre", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_008", nome: "Pedra branca e rosa", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_009", nome: "Dedão folha", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_010", nome: "V", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_011", nome: "Dedinho", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_012", nome: "Torcida rose", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_013", nome: "Pingo verde", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "anel_014", nome: "Preto", marca: "", tipo: "outros", categoriaRoleta: "anel", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "base_001", nome: "Natura Una HD", marca: "Natura", tipo: "rosto", categoriaRoleta: "base", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "base_002", nome: "Niina Daily tint", marca: "Niina", tipo: "rosto", categoriaRoleta: "base", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "base_003", nome: "Mari m Baunilha", marca: "", tipo: "rosto", categoriaRoleta: "base", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "base_004", nome: "Missha 13", marca: "Missha", tipo: "rosto", categoriaRoleta: "base", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "base_005", nome: "Missha Blanc", marca: "Missha", tipo: "rosto", categoriaRoleta: "base", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "base_006", nome: "Fran Rosa", marca: "Fran", tipo: "rosto", categoriaRoleta: "base", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "base_007", nome: "Guava 05", marca: "Guava", tipo: "rosto", categoriaRoleta: "base", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "base_008", nome: "Guava 10", marca: "Guava", tipo: "rosto", categoriaRoleta: "base", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "base_009", nome: "QDB 01", marca: "QDB", tipo: "rosto", categoriaRoleta: "base", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "base_010", nome: "MMC 01", marca: "MMC", tipo: "rosto", categoriaRoleta: "base", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "base_011", nome: "Bt Skinplush", marca: "Bt", tipo: "rosto", categoriaRoleta: "base", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "base_012", nome: "Nars Vanilla", marca: "Nars", tipo: "rosto", categoriaRoleta: "base", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "cilios_001", nome: "MM Ginger lash", marca: "MM", tipo: "outros", categoriaRoleta: "cilios", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "cilios_002", nome: "Vizzela Brown", marca: "Vizzela", tipo: "outros", categoriaRoleta: "cilios", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "cilios_003", nome: "Vizzela Cherry", marca: "Vizzela", tipo: "outros", categoriaRoleta: "cilios", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "cilios_004", nome: "Guava preta", marca: "Guava", tipo: "outros", categoriaRoleta: "cilios", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "cilios_005", nome: "Guava marrom", marca: "Guava", tipo: "outros", categoriaRoleta: "cilios", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "cilios_006", nome: "Eudora turbo", marca: "Eudora", tipo: "outros", categoriaRoleta: "cilios", cor: "", funcao: "", combina: "", climas: [], ativo: true },
  { id: "cilios_007", nome: "Belas marrom", marca: "Belas", tipo: "outros", categoriaRoleta: "cilios", cor: "", funcao: "", combina: "", climas: [], ativo: true },
];
